// Builds the self-contained `awui` binary: the dist server plus the built web
// bundle and the harness extension sources, embedded, compiled to a native
// executable per target with `bun build --compile`. The web server is the
// product; `awui install tui` (a subcommand inside the binary) lays down the
// atui Bun script separately.
//
//   bun run scripts/build-binary.ts            # this machine's platform
//   bun run scripts/build-binary.ts --all      # every target (CI/release)
//
// Pipeline: `npm run build` (dist/server + dist/web), generate the embedded
// asset module, then compile. The generated module's import runs
// registerEmbeddedAssets() at startup, so the server serves the bundle from
// memory and materializes the extension sources into the state folder on first
// run of a harness chat.
import { $ } from "bun";
import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
process.chdir(root);

// The embeds read from dist/: build the server and web bundle first.
await $`npm run build`;

const ALL = process.argv.includes("--all");
const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".map": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".woff2": "font/woff2",
  ".webmanifest": "application/manifest+json",
};

/** Recursively collect dist/web into `/`-relative URL paths. */
async function webFiles(): Promise<string[]> {
  const out: string[] = [];
  const walk = async (dir: string, prefix: string) => {
    for (const name of await readdir(dir)) {
      const full = path.join(dir, name);
      const st = await stat(full);
      if (st.isDirectory()) await walk(full, `${prefix}${name}/`);
      else out.push(`${prefix}${name}`);
    }
  };
  await walk(path.join(root, "dist", "web"), "/");
  return out.sort();
}

// The extension sources ride in as text; they are written to disk at startup for -e.
const EXTENSIONS = ["rewind-to.ts", "render-html.ts", "eval-python.ts"];

/** The generated module the binary embeds: registers web files and extension sources. */
async function assetModule(): Promise<string> {
  const files = await webFiles();
  const webEntries: string[] = [];
  for (const abs of files) {
    const ext = path.extname(abs);
    // Source maps are huge and the binary has no debugger to read them; skip.
    if (ext === ".map") continue;
    const bytes = await readFile(path.join(root, "dist", "web", abs.slice(1)));
    const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";
    // Text assets go as a string; binary (icons, fonts) ride as base64 so bytes survive intact.
    if (contentType.startsWith("text/") || ext === ".json" || ext === ".webmanifest" || ext === ".svg") {
      webEntries.push(`  m.set(${JSON.stringify(abs)}, { text: ${JSON.stringify(bytes.toString("utf8"))}, contentType: ${JSON.stringify(contentType)} });`);
    } else {
      webEntries.push(`  m.set(${JSON.stringify(abs)}, { text: Buffer.from(${JSON.stringify(bytes.toString("base64"))}, "base64"), contentType: ${JSON.stringify(contentType)} });`);
    }
  }
  const extEntries: string[] = [];
  for (const name of EXTENSIONS) {
    const text = await readFile(path.join(root, "extensions", name), "utf8");
    extEntries.push(`  e.set(${JSON.stringify(name)}, ${JSON.stringify(text)});`);
  }
  return [
    `// Generated by scripts/build-binary.ts; the binary embeds it.`,
    `import { registerEmbeddedAssets } from "./embedded.js";`,
    `const m = new Map();`,
    ...webEntries,
    `const e = new Map();`,
    ...extEntries,
    `registerEmbeddedAssets(m, e);`,
  ].join("\n");
}

const assetSource = await assetModule();
const assetPath = path.join(root, "src", "server", "assets.gen.ts");
const stubSource = await readFile(assetPath, "utf8");

const commit = (await $`git rev-parse HEAD`.text()).trim();
const repo = (await $`git remote get-url origin`.text()).trim().replace(/^git@([^:]+):/, "https://$1/").replace(/\.git$/, "");

const targets = ALL
  ? ["bun-linux-x64", "bun-linux-arm64", "bun-darwin-x64", "bun-darwin-arm64", "bun-windows-x64"]
  : [`bun-${process.platform}-${process.arch}`] as const;

// The generated module is the embed payload: write it, then recompile just it into
// dist (the earlier npm build compiled the checked-in stub), so the bundle carries it.
await Bun.write(assetPath, assetSource);
await $`npx tsc -p tsconfig.server.json`;
try {
  for (const target of targets) {
    const name = target.replace(/^bun-/, "");
    const outDir = path.join(root, "dist", "bin", name);
    await $`mkdir -p ${outDir}`;
    const outfile = path.join(outDir, name.includes("windows") ? "awui.exe" : "awui");
    console.log(`compiling awui ${pkg.version} → ${name}`);
    await Bun.build({
      // Compile the built JS, not the TS source: the bundler already resolved it,
      // and a raw-TS entry plus the generated module hit a bun --compile crash here.
      entrypoints: ["./dist/server/server/index.js"],
      format: "esm",
      minify: true,
      sourcemap: "none",
      target: "bun",
      compile: { target: target as import("bun").CompileTarget, outfile },
      define: {
        AWUI_EMBEDDED: "true",
        AWUI_VERSION: JSON.stringify(pkg.version),
        AWUI_COMMIT: JSON.stringify(commit),
        AWUI_REPO: JSON.stringify(repo),
      },
    });
    console.log(`  → ${outfile}`);
  }
} finally {
  await Bun.write(assetPath, stubSource);
}

console.log("done.");
